Test:
  image: debian:bookworm
  tags: ['ace-x86_64']
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install curl git python3 python3-pip python3-venv > /dev/null 2> /dev/null
    - python3 -m venv .venv && source .venv/bin/activate
  script:
    - pip3 install --break-system-packages .
    - ./tests/test.sh
