Test:
  image: ubuntu:20.04
  tags: ['ace-x86_64']
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - apt -qqy update > /dev/null 2> /dev/null
    - apt -qqy install curl git python3 python3-pip python3-venv libicu66 > /dev/null 2> /dev/null
  script:
    - python3 -m venv .venv && source .venv/bin/activate
    - pip3 install .
    - ./tests/test.sh
