name: Renode-run test
on:
  push:
  schedule:
    - cron: '0 23 * * *' # run daily at 23:00 (UTC)

jobs:
  test-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install prerequisites
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip

      - name: Install renode-run
        run: |
          python3 -m venv .venv && source .venv/bin/activate
          python3 -m pip install .

      - name: Run renode-run
        run: |
          source .venv/bin/activate
          renode-run --help
          renode-run download

      - name: Run renode-run tests
        run: |
          source .venv/bin/activate
          ./tests/test.sh

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Install renode-run
        run: |
          python -m venv .venv
          .venv\Scripts\Activate.ps1
          python -m pip install .

      - name: Run renode-run
        run: |
          .venv\Scripts\Activate.ps1
          renode-run --help
          renode-run download

      - name: Run renode-run tests
        shell: bash
        run: |
          source .venv/Scripts/activate
          ./tests/test.sh
